controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home_about:
    controller: \App\Controller\HomeController::about
    path: /about
